server:
  port: 8030
  servlet:
    context-path: /uaa

jwt:
  certificate:
    store:
      file: classpath:/certificate/mykeystore.jks
      password: abirkhan04
    key:
      alias: myauthkey
      password: abirkhan04

spring:
  application:
    name: auth-service

  datasource:
    driver-class-name: org.postgresql.Driver
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql

  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

authentications:
  clean:
    cron: 0 30 * * * *