version: "3"
services:
  postgres:
    image: postgres:13.0
    container_name: cloud-movies-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=movies-users

  mongo:
    image: mongo:4.4.0
    container_name: cloud-movies-mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=movies-list
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=password

  rabbit:
    image: rabbitmq:3-management
    container_name: cloud-movies-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis:6.0
    container_name: cloud-movies-redis
    ports:
      - 6379:6379

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: cloud-movies-elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "discovery.type=single-node"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.0
    container_name: cloud-movies-logstash
    links:
      - elasticsearch:elasticsearch
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logs:/usr/share/logstash/logs

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    container_name: cloud-movies-kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS:http://elasticsearch:9200
    links:
      - elasticsearch:elasticsearch

  zipkin:
    image: openzipkin/zipkin
    container_name: cloud-movies-zipkin
    ports:
      - 9411:9411

  graphite:
    image: graphiteapp/graphite-statsd
    container_name: cloud-movies-graphite
    ports:
      - 2003:2003
      - 2004:2004
      - 2023:2023
      - 2024:2024
      - 8125:8125/udp
      - 8126:8126

  graphana:
    image: grafana/grafana
    container_name: cloud-movies-grafana
    ports:
      - 3000:3000
    links:
      - graphite:graphite
      - elasticsearch:elasticsearch
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/