server:
  port: 0

spring:
  application:
    name: movies-list-service

  servlet:
    multipart:
      enabled: true
      max-file-size: 256MB
      max-request-size: 256MB

info:
  project:
    name: @project.name@
    version: @project.version@
    artifactId: @project.artifactId@
    groupId: @project.groupId@