spring:
  application:
    name: gateway-service

zuul:
  ignored-services: "*"
  sensitive-headers: Cookie,Set-Cookie
  routes:
    users:
      path: /users/**
      serviceId: user-resource-service

logging:
  level:
    org:
      springframework:
        security:
          web:
            csrf:
              CsrfFilter: debug