spring:
  application:
    name: gateway-service
  session:
    store-type: redis

zuul:
  sensitive-headers: Authorization,Cookie,Set-Cookie
  routes:
    users:
      path: /users/**
      serviceId: user-resource-service

logging:
  level:
    org:
      springframework:
        security:
          web:
            csrf:
              CsrfFilter: debug