spring:
  application:
    name: gateway-service
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 256MB
      max-request-size: 256MB

zuul:
  ignored-services: "*"
  sensitive-headers: Cookie,Set-Cookie
  routes:
    users:
      path: /users/**
      serviceId: user-resource-service
    movies:
      path: /movies/**
      serviceId: movies-list-service

logging:
  level:
    org:
      springframework:
        security:
          web:
            csrf:
              CsrfFilter: debug

security:
  oauth2:
    resource:
      userInfoUri: http://user-resource-service/profile