package com.movies.list.movies

enum class MoviesGenres {
    ABSURDIST,
    ACTION,
    ADVENTURE,
    COMEDY,
    CRIME,
    DRAMA,
    FANTASY,
    HISTORICAL,
    HISTORICAL_FICTION,
    HORROR,
    MAGICAL_REALISM,
    MYSTERY,
    PARANOID_FICTION,
    PHILOSOPHICAL,
    POLITICAL,
    ROMANCE,
    SAGA,
    SATIRE,
    SCIENCE_FICTION,
    SOCIAL,
    SPECULATIVE,
    THRILLER,
    URBAN,
    WESTERN
}