{
 "title": "Main",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Movies count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "movies.count" }
   ]
  },
  {
   "title": "Registered - Deleted users",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "users.registered.count" },
    { "target": "users.deleted.count" },
    { "target": "users.registered" }
   ]
  },
  {
   "title": "Login - Logout",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "account.login.un_success.count" },
    { "target": "account.login.success.count" },
    { "target": "account.logout.success.count" }
   ]
  },
  {
   "title": "Users count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "users.count" }
   ]
  }
 ]
}