services:
  eureka-service:
    username: user
    password: pass

eureka:
  client:
    serviceUrl:
      defaultZone: "http://${services.eureka-service.username}:${services.eureka-service.password}@localhost:8020/eureka"