services:
  eureka-service:
    username: user
    password: pass

databases:
  users:
    url: jdbc:postgresql://localhost:5432/movies-users
    username: postgres
    password: password
  movies:
    host: localhost
    port: 27017
    authentication-database: admin
    database: movies-list
    username: mongodb
    password: password

jwt:
  keyValue: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhiiifKv6Otf5PyqIE+LQ
    EiJRRh6q8piPY9Okq+RfRu9Bue0D8hq7aFxcgkLZ6Bg9CAS+w1KdaE5MMeOCVVxv
    rpRETzVpAsh6GL5nBc679jSqMzjr3V4uty46ilL4VHKSxlZh5Nmz5EMHPI5iwpNs
    8U5n3QiwsTk514FXad54xPSPH3i/pDzGSZHrVcwDVaOKn7gFiIqP86vkJB47JZv8
    T6P5RK7Rj06zoG45DMGWG3DQv6o1/Jm4IJQWj0AUD3bSHqzXkPr7qyMYvkE4kyMH
    6aVAsAYMxilZFlJMv2b8N883gdi3LEeOJo8zZr5IWyyROfepdeOL7UkAXddAj+dL
    WQIDAQAB
    -----END PUBLIC KEY-----

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: "http://${services.eureka-service.username}:${services.eureka-service.password}@localhost:8020/eureka"

management:
  endpoints:
    web:
      exposure:
        include: "*"