services:
  eureka-service:
    username: user
    password: pass

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: "http://${services.eureka-service.username}:${services.eureka-service.password}@localhost:8020/eureka"