oauth2:
  clients:
    - id: ${oauth2.client.clientId}
      secret: ${oauth2.client.password}
      redirectUri: http://localhost:8080/login
      authorizedGrantTypes:
        - authorization_code
        - refresh_token
      scopes: user_info
      autoApprove: true
      accessTokenValiditySeconds: 3600
      refreshTokenValiditySeconds: 86400

spring:
  datasource:
    url: ${databases.users.url}
    username: ${databases.users.username}
    password: ${databases.users.password}
    initialization-mode: always

  zipkin:
    enabled: ${zipkin.enabled}
    sender:
      type: web
    base-url: ${zipkin.base-url}

eureka:
  instance:
    hostname: 127.0.0.1