security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8030/uaa/oauth/token
      userAuthorizationUri: http://127.0.0.1:8030/uaa/oauth/authorize
      clientId: ${oauth2.client.clientId}
      clientSecret: ${oauth2.client.password}

eureka:
  instance:
    hostname: localhost

spring:
  zipkin:
    enabled: ${zipkin.enabled}
    sender:
      type: web
    base-url: ${zipkin.base-url}