security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8030/uaa/oauth/token
      userAuthorizationUri: http://127.0.0.1:8030/uaa/oauth/authorize
      clientId: testClient
      clientSecret: password

eureka:
  instance:
    hostname: localhost