security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8030/uaa/oauth/token
      userAuthorizationUri: http://localhost:8030/uaa/oauth/authorize
      clientId: testClient
      clientSecret: password
    resource:
      userInfoUri: http://10.0.114.148:8040/profile