spring:
  data:
    mongodb:
      host: ${databases.movies.host}
      port: ${databases.movies.port}
      authentication-database: ${databases.movies.authentication-database}
      database: ${databases.movies.database}
      username: ${databases.movies.username}
      password: ${databases.movies.password}