security:
  oauth2:
    resource:
      jwt:
        keyValue: ${jwt.keyValue}

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: movies-list
      username: mongodb
      password: password

  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

  zipkin:
    enabled: true
    sender:
      type: web
    base-url: ${zipkin.base-url}