security:
  oauth2:
    resource:
      jwt:
        keyValue: ${jwt.keyValue}

spring:
  datasource:
    url: ${databases.users.url}
    username: ${databases.users.username}
    password: ${databases.users.password}

  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

  zipkin:
    enabled: true
    sender:
      type: web
    base-url: ${zipkin.base-url}