security:
  oauth2:
    resource:
      jwt:
        keyValue: ${jwt.keyValue}

spring:
  datasource:
    url: ${databases.users.url}
    username: ${databases.users.username}
    password: ${databases.users.password}
