server:
  port: 8040

spring:
  application:
    name: user-resource-service

  datasource:
    driver-class-name: org.postgresql.Driver
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql

  session:
    store-type: redis