server:
  port: 8020
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

info:
  project:
    name: @project.name@
    version: @project.version@
    artifactId: @project.artifactId@
    groupId: @project.groupId@