spring:
  application:
    name: config-service
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/Munoon/Cloud-Movies-List.git"
          clone-on-start: true
          force-pull: true
          search-paths: config
  security:
    user:
      name: test
      password: test

server:
  port: 8010
