spring:
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/Munoon/Cloud-Movies-List.git"
          clone-on-start: true
          force-pull: true
          search-paths: config
