spring:
  application:
    name: config-service

  security:
    user:
      name: test
      password: test

server:
  port: 8010

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

info:
  project:
    name: @project.name@
    version: @project.version@
    artifactId: @project.artifactId@
    groupId: @project.groupId@