spring:
  application:
    name: config-service

  security:
    user:
      name: test
      password: test

server:
  port: 8010

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh